# https://aka.ms/yaml

stages:
- stage: 'DeployLinux'
  dependsOn: []
  jobs:
  - job: build_linux # name of the deployment job (A-Z, a-z, 0-9, and underscore)
    displayName: 'DeployLinuxWithDockcross' # friendly name to display in the UI
    timeoutInMinutes: 0
    pool:                # see the following "Pool" schema
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Bash@3
      inputs:
        filePath: '$(Build.SourcesDirectory)/deploy/deploy_linux.sh'
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/deploy/dist/'
        artifactName: 'LinuxWheels'

- stage: 'DeployMacOS'
  dependsOn: []
  pool:
    vmImage: 'macOS-10.15'
  variables:
    DEPENDENCIES_BUILD_DIR: $(Agent.BuildDirectory)/build_deps
  jobs:
  - job: build_macos
    displayName: 'Build project and deploy'
    timeoutInMinutes: 0
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - task: Bash@3
      inputs:
        filePath: '$(Build.SourcesDirectory)/deploy/deploy_macos_one_python.sh'
        workingDirectory: '$(Build.SourcesDirectory)'
      displayName: 'Build project'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/deploy/dist/'
        artifactName: 'MacOSWheel$(python.version)'

- stage: 'DeployWindows'
  dependsOn: []
  pool:
    vmImage: 'windows-2019'
  variables:
    DEPENDENCIES_BUILD_DIR: $(Agent.BuildDirectory)/build_deps
  jobs:
  - job: build_win
    displayName: 'Build project and deploy'
    timeoutInMinutes: 0
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        python -m pip install -r requirements-deploy.txt
        python setup.py bdist_wheel --build-type Release -G Ninja -- -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe" -DPERM_BUILD_TESTING:BOOL=OFF -DPERM_WRAP_PYTHON:BOOL=ON
      workingDirectory: '$(Build.SourcesDirectory)\deploy'
      displayName: 'Build project'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.SourcesDirectory)/deploy/dist
        artifactName: 'WindowsWheel$(python.version)'
