FROM dockcross/manylinux2014-x64
LABEL MAINTAINER="Pablo Hernandez Cerdan <pablo.hernandez.cerdan@outlook.com>"

###################### PERM #############
ENV BUILD_PATH /work
WORKDIR $BUILD_PATH
ENV PERM_CMAKE_BUILD_TYPE Release
ENV PERM_BUILD_DIR ${BUILD_PATH}/PERM-build
ENV PERM_SRC_FOLDER_NAME PERM-src
ENV PERM_SRC_DIR ${BUILD_PATH}/${PERM_SRC_FOLDER_NAME}

# Copy files from current repo into the docker container
COPY . ${PERM_SRC_DIR}
# Remove _skbuild and dist folders if existant
# RUN cd ${PERM_SRC_DIR} && rm -rf ./deploy/_skbuild && rm -rf ./deploy/dist

WORKDIR ${PERM_SRC_DIR}/deploy

RUN ${PERM_SRC_DIR}/deploy/scripts/manylinux-build-wheels.sh

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG IMAGE=perm-linux-wheel
ARG VERSION=latest
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0" \
      build_command="\
      docker build -f ./deploy/docker/Dockerfile-dockcross-manylinux2014-wheel . -t phcerdan/perm-linux-wheel; \
      docker cp $(docker create phcerdan/perm-linux-wheel:latest):/work/dist /tmp"
